# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron Addleman
owner: Aaron Addleman
author: Aaron Addleman
email: your-email@domain.com
description: > 
  Archived thoughts, technical experiments, notes, and media created by myself.
  Take a look around and I welcome your comments on anything you see. Thanks for
  visiting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaronaddleman.com" # the base hostname & protocol for your site
permalink: /articles/:title
twitter_username: aaronaddleman
github_username: aaronaddleman
discus_shortname: aaronaddleman

# Build settings
markdown: kramdown

# Analytics
google_analytics: UA-31631239-1

# Webmaster Tools
google_verify:
bing_verify:

<<<<<<< HEAD
# Style
sass:
  sass_dir: _sass
  style: compressed

redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data

# syntax coloring
highlighter: rouge
=======
# Links to include in top navigation
# For external links add external: true
links:
  - title: Resume
    url: /resume
  # - title: External Link
    # url: http://mademistakes.com
    # external: true

code_path: "/assets/files"
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
#pygments:    true
#highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /articles/:title

# Amount of post to show on home page
paginate: 6

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "divshot.json", ".ruby-gemset", ".ruby-version"]
gems:
  - jekyll-sitemap
>>>>>>> 68efee43dbd875d95a6c8fbc19e4ff7e4743b6df
